import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-gpu', '--use-angle=d3d11'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on('pageerror', (e) => console.log('pageerror', String(e)));
await page.goto('http://localhost:5173/#/overview', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__ENCIRRA__?.sim.getState().ready);
await page.waitForTimeout(3000);
await page.keyboard.press('Control+k');
await page.waitForTimeout(300);
console.log('open after ctrl+k:', await page.evaluate(() => window.__ENCIRRA__.ui.getState().paletteOpen));
await page.keyboard.type('Radiological Scenario');
await page.waitForTimeout(300);
const opts = await page.locator('[role="option"]').allInnerTexts();
console.log('options:', opts.slice(0, 5));
await page.keyboard.press('Enter');
await page.waitForTimeout(1500);
console.log('open after enter:', await page.evaluate(() => window.__ENCIRRA__.ui.getState().paletteOpen));
console.log('run:', await page.evaluate(() => JSON.stringify(window.__ENCIRRA__.sim.getState().run)));
await page.screenshot({ path: process.argv[2] });
await browser.close();
